# Generated by Django 3.0 on 2021-01-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='products/product_images/categ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='products/product_images'),
        ),
    ]
