# Generated by Django 3.0 on 2021-01-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210102_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_img',
            new_name='product_categ_img',
        ),
    ]
